### ISSUE TITLE
Need GitHub workflow for PyPI releases.

### ISSUE THREAD

**Issue by krister-ts** [ftd2xx/ftd2xx-aio#1]
@snmishra I'm not too familiar with setting up PyPI. Could you make release workflow and then make project public?

**Comment by snmishra** [comment]
Is it ok to publish under my credentials in PyPI. I have that configured and can set this repo up to do the same.

**Comment by krister-ts** [comment]
> Is it ok to publish under my credentials in PyPI. I have that configured and can set this repo up to do the same.

Absolutey!

**Comment by krister-ts** [comment]
@snmishra When PyPI is ready, you can make a release and also change this project to public.

**Comment by snmishra** [comment]
Done. https://pypi.org/project/ftd2xx-aio/. If you have a PyPI account @krister-ts, I can add you as an owner there as well.
